# Generated by Django 6.0.5 on 2026-05-24 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='extracted_text',
        ),
    ]
