# Generated by Django 6.0.5 on 2026-05-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_conversation_options_alter_message_options'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='messages', to='files.file'),
        ),
    ]
