# Generated by Django 6.0.5 on 2026-05-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='log',
            field=models.TextField(blank=True),
        ),
    ]
